ignore:
  # This is just a script to generate type defs for the frontend, nothing to test
  - "frontend/generate_types.rs"
  # Derivations for basic Display and Debug impls, nothing to test
  - "simple-secrecy/src"
  # The main file is not really testable
  - "backend/src/main.rs"
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0%
