name: e2e-tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  e2e-tests:
    name: e2e ${{ matrix.browser }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "7.29.0"
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: pnpm install
      - uses: Swatinem/rust-cache@v2
      - run: pnpx playwright install --with-deps ${{ matrix.browser }} chromium
      - name: Run the tests
        run: |
          # cleanup test user storage
          pushd ../bulgur-cloud-backend
          rm -rf storage/testuser
          cargo run user add --username testuser --password testpass

          # Run in the background
          cargo run &

          # Wait until the server is ready
          while true; do
            curl --head http://localhost:8000/is_bulgur_cloud && break || sleep 1
          done

          popd
          # Run the tests
          pnpm run test --project=${{ matrix.browser }}
