name: release
on:
  push:
    branches:
      - release/*
jobs:
  release-builds:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install UI deps
        run: npm install
        working-directory: frontend
      - name: Build UI
        run: npm build
        working-directory: frontend
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Get final build
        run: cross build --release --target ${{ matrix.target }}
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: bulgur-cloud-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/bulgur-cloud*

  # This block is from `e2e.yml`, make sure you change both together.
  e2e-tests:
    name: e2e ${{ matrix.browser }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - run: npm install
      - uses: Swatinem/rust-cache@v2
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - name: Run the tests
        run: |
          # cleanup test user storage
          pushd ../backend
          rm -rf storage/testuser
          cargo run user add --username testuser --password testpass

          # Run in the background
          cargo run &

          # Wait until the server is ready
          while true; do
            curl --head http://localhost:8000/is_bulgur_cloud && break || sleep 1
          done

          popd
          # Run the tests
          npm run test -- --project=${{ matrix.browser }}


  backend-tests:
    name: backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run backend tests
        run: cargo test -- --test-threads=1

  compile-release:
    name: Compile release
    runs-on: ubuntu-latest
    needs: [release-builds, e2e-tests, backend-tests]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Calculate version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed -E 's/^release[/](.*)$/\1/')
          echo version=${VERSION} | tee -a "$GITHUB_OUTPUT"
        # Downloaded artifacts are put into awkward folders, and they lose their permissions.
        # So let's collect them into a single directory and mark them as executable.
      - name: Collect downloaded artifacts
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p release-artifacts
          cp bulgur-cloud-aarch64-unknown-linux-musl/bulgur-cloud release-artifacts/bulgur-cloud.${VERSION}.linux-aarch64
          cp bulgur-cloud-arm-unknown-linux-musleabihf/bulgur-cloud release-artifacts/bulgur-cloud.${VERSION}.linux-armv6
          cp bulgur-cloud-armv7-unknown-linux-musleabihf/bulgur-cloud release-artifacts/bulgur-cloud.${VERSION}.linux-armv7
          cp bulgur-cloud-x86_64-pc-windows-gnu/bulgur-cloud.exe release-artifacts/bulgur-cloud.${VERSION}.windows-x86_64.exe
          cp bulgur-cloud-x86_64-unknown-linux-musl/bulgur-cloud release-artifacts/bulgur-cloud.${VERSION}.linux-x86_64
          chmod +x release-artifacts/*
        # Sign the artifacts! Ensures any downloaded artifacts came from this build process.
      - name: Sign and prepare artifacts
        run: |
          echo "${SIGNING_PRIVATE_KEY}" | gpg --import -

          cd release-artifacts
          for file in * ; do
            gpg --detach-sign "$file"
          done

          for file in *.linux-* ; do
            tar -acf "${file}.tar.xz" "$file"
          done
          for file in *.windows-* ; do
            zip "${file}.zip" "$file"
          done
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
        # Create a draft release. The description can be manually created afterwards.
      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-artifacts/*.tar.xz,release-artifacts/*.zip,release-artifacts/*.sig
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true
          removeArtifacts: true
          commit: ${{ github.ref_name }}
          tag: release/${{ steps.version.outputs.version }}
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: bulgur-cloud
          password: ${{ secrets.GITHUB_TOKEN }}
        # We need to put the binaries into specific folders then run the docker build with buildx
      - name: Prepare to build docker images
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p Docker/binaries/linux/amd64 Docker/binaries/linux/arm64 Docker/binaries/linux/arm/v6 Docker/binaries/linux/arm/v7
          cd Docker
          cp ../release-artifacts/bulgur-cloud.${VERSION}.linux-aarch64 binaries/linux/arm64/bulgur-cloud
          cp ../release-artifacts/bulgur-cloud.${VERSION}.linux-armv6 binaries/linux/arm/v6/bulgur-cloud
          cp ../release-artifacts/bulgur-cloud.${VERSION}.linux-armv7 binaries/linux/arm/v7/bulgur-cloud
          cp ../release-artifacts/bulgur-cloud.${VERSION}.linux-x86_64 binaries/linux/amd64/bulgur-cloud
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: seriousbug/bulgur-cloud:latest,seriousbug/bulgur-cloud:${{ steps.version.outputs.version }},ghcr.io/bulgur-cloud/bulgur-cloud:latest,ghcr.io/bulgur-cloud/bulgur-cloud:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          context: ./Docker
